version: '3'

node-chrome:
images: selenium/node-chrome
environment:
        -SE_EVENT_BUS_HOST=selenium-hub
        -SE_EVENT_BUS_PUBLISH_PORT=4442
        -SE_EVENT_BUS_SUBSCRIBE_PORT=4443
        networks:
        -grid
        
        node-edge:
images: selenium/node-edge
environment:
        -SE_EVENT_BUS_HOST=selenium-hub
        -SE_EVENT_BUS_PUBLISH_PORT=4442
        -SE_EVENT_BUS_SUBSCRIBE_PORT=4443
        networks:
        -grid
        
        node-firefox:
images: selenium/node-firefox 
environment:
        -SE_EVENT_BUS_HOST=selenium-hub
        -SE_EVENT_BUS_PUBLISH_PORT=4442
        -SE_EVENT_BUS_SUBSCRIBE_PORT=4443
        networks:
        -grid
        
        
networks:
grid:
   driver:brodge        